config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show'
  post 'users/edit', to: 'users#update'

  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :gigs

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name])
  end

  def after_sign_in_path_for(_resource)
    dashboard_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard; end

  def update
    @user = current_user
    flash[:notice] =
      @user.update(current_user_params) ? 'Saved...' : 'Cannot update...'
    redirect_to dashboard_path
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.avatar.attached?
      url_for(user.avatar)
    else
      ActionController::Base.helpers.asset_path('icon_default_avatar.png')
    end
  end

  def gig_cover(gig)
    if gig.photos.attached?
      url_for(gig.photos[0])
    else
      ActionController::Base.helpers.asset_path('icon_default_avatar.png')
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freelancer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notification' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

app/views/shared/_navbar.html.erb
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <h1 class='title is-4'>Freelancer</h1>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class='navbar-start'>
      <div class='navbar-item'>
        <div class="field has-addons">
          <div class="control">
            <input class='input' type="text" placeholder="Find services" />
          </div>
          <div class="control">
            <a class="button is-danger">
              Search
            </a>
          </div>
        </div>
      </div> 
    </div>

    <div class="navbar-end">
      <%= link_to 'Post Gig', new_gig_path, class: 'navbar-item' %>
      <a class="navbar-item">Browse Gigs</a>

      <% if !user_signed_in? %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to "Sign Up", new_user_registration_path, class: 'button is-primary' %>
            <%= link_to "Login", new_user_session_path, class: 'button is-primary' %>
          </div>
        </div>
      <% else %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <figure class='image is-24x24 m-r-5'>
              <%= image_tag avatar_url(current_user), class: 'is-rounded' %>
            </figure>
            <%= current_user.full_name %>
          </a>
          <div class="navbar-dropdown">
            <%= link_to "Profile", edit_user_registration_path, class: 'navbar-item' %>
            <%= link_to "Dashboard", dashboard_path, class: 'navbar-item' %>
            <hr class="navbar-divider">
            <%= link_to "Logout", destroy_user_session_path, method: :delete,  class: 'navbar-item' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

<% if user_signed_in? && !current_page?(root_path) && !current_page?('/gigs/#{params[:id]}') && !current_page?('/users/#{params[:id]}') %>
  <nav class='navbar has-shadow' style="z-index: 5">
    <div class="container">
      <div class="navbar">
        <%= link_to "Dashboard", dashboard_path, class: 'navbar-item' %>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Selling</a>
          <div class="navbar-dropdown">
            <%= link_to 'Create New Gig', new_gig_path, class: 'navbar-item' %>
          </div>
        </div>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Buying</a>
          <div class="navbar-dropdown">
            <%= link_to "Post Request", edit_user_registration_path, class: 'navbar-item' %>
            <%= link_to "Manage Request", edit_user_registration_path, class: 'navbar-item' %>
          </div>
        </div>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Buyer Requests</a>
          <div class="navbar-dropdown">
            <%= link_to "Active Request", edit_user_registration_path, class: 'navbar-item' %>
            <%= link_to "Offers Sent", edit_user_registration_path, class: 'navbar-item' %>
          </div>
        </div>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Orders</a>
          <div class="navbar-dropdown">
            <%= link_to "Selling Orders", edit_user_registration_path, class: 'navbar-item' %>
            <%= link_to "Buying Orders", edit_user_registration_path, class: 'navbar-item' %>
          </div>
        </div>

        <%= link_to "Earnings", dashboard_path, class: 'navbar-item' %>
        <%= link_to "Messages", dashboard_path, class: 'navbar-item' %>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">Settings</a>
          <div class="navbar-dropdown">
            <%= link_to "Payment Method", edit_user_registration_path, class: 'navbar-item' %>
            <%= link_to "Payout Method", edit_user_registration_path, class: 'navbar-item' %>
          </div>
        </div>

      </div>
    </div>
  </nav>
<% end %>
<script>
  $(document).ready(function() {
    $(".navbar-burger").click(function() {
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");
    });
  });
</script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |key, value| %> 
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      new Noty({
        type: '<%= type %>',
        layout: 'topRight',
        timeout: '3000',
        theme: 'sunset',
        text: '<%= value %>'
      }).show()
    <% end %>
  </script>
<% end %>

app/views/users/dashboard.html.erb
<section class="section">
  <div class="container">
    <div class="columns">

      <!-- LEFT SIDE -->
      <div class="column is-one-third">
        <div class="columns is-multiline">

          <!-- Top Card -->
          <div class="column is-full">
            <div class="card">

              <!-- Avatar -->
              <div class="card-content is-horizontal-center is-flex">
                <figure class='image is-128x128'>
                  <%= image_tag avatar_url(current_user), class: 'is-rounded' %>
                </figure>
              </div>

              <div class="card-content">

                <!-- Upload Button -->
                <div class="content has-text-centered">
                  <p class='title is-5'>
                    <%= current_user.full_name %>
                  </p>
                  <%= form_with scope: :user, url: users_edit_url(@user) do |f| %>
                    <div class='file'>
                      <label class='button is-primary is-outlined is-fullwidth'>
                        <%= f.file_field :avatar, class: 'file-input', onchange: 'this.form.submit()' %>
                        <i class="fas fa-upload"></i> &nbsp; Upload Avatar
                      </label>
                    </div>
                  <% end %>
                </div>
                <hr class="h-10">

                <!-- Member -->
                <article class="media">
                  <div class='media-content'>
                    Member since 
                  </div>
                  <div class='media-right'>
                    <strong><%= current_user.created_at.strftime('%b %Y') %></strong> 
                  </div>
                </article>
                <hr class="h-10">

                <!-- From -->
                <article>
                  <div class='media'>
                    <div class='media-content'>
                      From 
                    </div> 
                    <div class='media-right'>
                      <strong><%= current_user.from %></strong> 
                      <i class='toggle far fa-edit' aria-controls='user-from'></i>
                    </div>
                  </div>
                  <div class='content'>
                    <%= form_with scope: :user, url: users_edit_url(@user), id: 'user-from', class: 'is-hidden' do |f| %>
                      <div class='field'>
                        <%= f.text_field :from, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>
                      <a class='toggle button is-light' aria-controls='user-from'>Cancel</a>
                      <%= f.submit 'Save', class: 'button is-danger' %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Online Status -->
                <article>
                  <div class='media'>
                    <div class='media-content'>
                      Status 
                    </div> 
                    <div class='media-right'>
                      <strong><% if current_user.status %> Online <% else %> Offline <% end %></strong> 
                      <i class='toggle far fa-edit' aria-controls='user-status'></i>
                    </div>
                  </div>

                  <div class='content'>
                    <%= form_with scope: :user, url: users_edit_url(@user), id: 'user-status', class: 'is-hidden' do |f| %>
                      <div class='field'>
                        <%= f.select :status, options_for_select([['Online', true], ['Offline', false]]), {}, {class: 'select is-fullwidth'} %>
                      </div>
                      <a class='toggle button is-light' aria-controls='user-status'>Cancel</a>
                      <%= f.submit 'Save', class: 'button is-danger' %>
                    <% end %>
                  </div>
                </article>

              </div>
            </div>
          </div>

          <!-- Bottom Card -->
          <div class="column is-full">
            <div class="card">
              <div class="card-content">

                <!-- About -->
                <article>
                  <div class='media'>
                    <div class='media-content'>
                      <p>
                        <strong>About Yourself</strong>
                        <br>
                        <%= current_user.about %>
                      </p> 
                    </div> 
                    <div class='media-right'>
                      <i class='toggle far fa-edit' aria-controls='user-about'></i>
                    </div>
                  </div>
                  <div class='content'>
                    <%= form_with scope: :user, url: users_edit_url(@user), id: 'user-about', class: 'is-hidden' do |f| %>
                      <div class='field'>
                        <%= f.text_area :about, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>
                      <a class='toggle button is-light' aria-controls='user-about'>Cancel</a>
                      <%= f.submit 'Save', class: 'button is-danger' %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Language -->
                <article>
                  <div class='media'>
                    <div class='media-content'>
                      <p>
                        <strong>Language</strong>
                        <br>
                        <%= current_user.language %>
                      </p> 
                    </div> 
                    <div class='media-right'>
                      <i class='toggle far fa-edit' aria-controls='user-language'></i>
                    </div>
                  </div>
                  <div class='content'>
                    <%= form_with scope: :user, url: users_edit_url(@user), id: 'user-language', class: 'is-hidden' do |f| %>
                      <div class='field'>
                        <%= f.text_field :language, autofocus: true, autocomplete: 'form', class: 'input' %>
                      </div>
                      <a class='toggle button is-light' aria-controls='user-language'>Cancel</a>
                      <%= f.submit 'Save', class: 'button is-danger' %>
                    <% end %>
                  </div>
                </article>
                <hr class="h-10">

                <!-- Linked Account -->
                <article class="media"></article>

              </div>
            </div>
          </div>

        </div>
      </div>

      <!-- RIGHT SIDE -->
      <div class="column">
        <div class="columns is-multiline">

          <!-- Create New Gig -->
          <div class="column is-one-third has-text-centered">
            <%= link_to new_gig_path do %>
              <div class="card">

                <div class="card-image card-content is-horizontal-center is-flex ">
                  <figure class="image is-128x128 ">
                    <%= image_tag 'icon_add.png' %>
                  </figure>
                </div>

                <div class="card-content">
                  <strong>Create a new gig</strong>
                </div>

              </div>
            <% end %>
          </div>


          <!-- Sample Gig -->
          <% current_user.gigs.each do |gig| %>
            <div class="column is-one-third">
              <div class="card">

                <div class="card-image">
                  <%= link_to edit_gig_path gig do %>
                    <figure class="image is-4by3">
                      <%= image_tag gig_cover gig %>
                    </figure>
                  <% end %>
                </div>

                <div class="card-content p-t-5 p-b-5">
                  <p class="subtitle is-6 m-b-5"><%= link_to gig.title, gig_path(gig) %></p>
                  <span class="star-review"><i class="fa fa-star"></i>
                    4.8 <span class="has-text-primary">(23)</span>
                  </span>
                </div>

                <footer class="card-footer">
                  <% basic_price = gig.pricings.find { |p| p.pricing_type == 'basic' } %>
                  <a class="has-text-danger is-block card-footer-item has-text-right">
                    <% if !basic_price.nil? %>
                      
                    <span class="small-title">STARTING AT</span> 
                    <strong>$<%= basic_price.price %></strong>                                            
                    <% else %>
                      <strong>
                        <span class="small-title has-text-dark">NO PRICING YET</span>
                      </strong>
                    <% end %>
                  </a>
                </footer>  

              </div>
            </div>
          <% end %>

          <!-- Sample Gig -->
          <div class="column is-one-third has-text-centered"></div>

        </div>
      </div>

    </div>
  </div>
</section>